### ISSUE TITLE
git reset (1.16) has error: undefined method 'upcase' for nil:NilClass

### ISSUE THREAD

**Issue by cookiengineer** [Try-Git/try_git#12]
Currently, there seems to be an error occuring in `1.16: Resetting the Stage`. People can't proceed further because of that.

How and where to fix that? There's no hint on what repository actually contains the source code for this tutorial, so people can't fix those kind of bugs. All your repositories are empty, which is kind of a shame.

[Screenshot of Error](http://i.imgur.com/m6gSrjz.png)

**Comment by rochastuff** [comment]
Hi cookienginner, I just tried it and it works. What I see in your screenshot, is that you are not typing the complete command, please try it again and type: **git reset octofamily/octodog.txt**

It should work now. remember that to do the exercise correctly, you have to type the text in blue showed in the tutorial.
