### ISSUE TITLE
Octodog failing tests in current test environment

### ISSUE THREAD

**Issue by Shakyamuni177te** [Try-Git/try_git#13]
In section _1:16_ of the **Code School** tutorial _Resetting the Stage_ it is written:

> Since we love octocat more than octodog

Yet it is not stated why you love octocat more than octodog. Suggest character development for future videos.

**Comment by GranularDetective** [comment]
Is this even worthy of a lol?

**Comment by Shakyamuni177te** [comment]
@GranularDetective How's Equine and Livestock?

**Comment by GranularDetective** [comment]
@Shakyamuni177te Wouldn't you like to know?

**Comment by Shakyamuni177te** [comment]
@GranularDetective I've moved on. I just hoped you were doing well in the company. I appreciate beauty can obscure talent but unfortunately I was not there long enough to tell the difference.

**Comment by GranularDetective** [comment]
@Shakyamuni177te See, dude's creepy as fuck. Get rid.

**Comment by Shakyamuni177te** [comment]
@GranularDetective How about the girl who moved on to Mood International. She had nice eyes.

**Comment by GranularDetective** [comment]
@Shakyamuni177te You pathetic, lonely little loser.

**Comment by GranularDetective** [comment]
@Shakyamuni177te I have a boyfriend. What do you have? Nothing.

**Comment by GranularDetective** [comment]
@Shakyamuni177te Like a dog with a bone. You can't let go, can you?

**Comment by GranularDetective** [comment]
It happened, I guess. And the stuff after... yeah. Well. I guess it's just thoughts now. I'll miss you. Please close this now.

**Comment by Shakyamuni177te** [comment]
GranularDe, this stuff needs deleting now. It's misleading at best.
